sonar.projectKey=demo
sonar.projectName=demo
sonar.java.source=21
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
sonar.junit.reportPaths=build/test-results/test
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.gradle.skipCompile=true
sonar.verbose=true
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
sonar.issuesReport.html.enable=true
sonar.issuesReport.console.enable=true
sonar.analysis.automatic=false 