services:
  mysql:
    image: mysql:8.0.42
    container_name: hospital_db
    env_file:
      - ./../.env # Loads environment variables from the .env file
    command:
      - --log_bin_trust_function_creators=1
    ports:
      - "7878:3306"
  mailHog:
    container_name: mailhog
    image: mailhog/mailhog
    env_file:
      - ./../.env # Loads environment variables from the .env file
    ports:
      - "8025:8025"
      - ${SMTP_PORT:-1025}:1025