version: '3.8'

services:
  mysql:
    image: mysql:8.0.42
    container_name: hospital_db
    env_file:
      - ./../.env # Loads environment variables from the .env file
    ports:
      - "7878:3306"